import { Helmet } from '@/lib/helmet-stub';
;
import { LandingFooter } from "@/components/landing/LandingFooter";

const Terms = () => {
  return (
    <>
      <Helmet>
        <title>Free AI Tool Terms of Service | Ultimate Freelancers</title>
        <meta name="description" content="Terms of Service for Ultimate Freelancers. Free to use with your own API key. No account, no signup required. Read our full usage and data handling terms." />
        <link rel="canonical" href="https://ultimatefreelancers.com/terms" />
        <meta property="og:title" content="Free AI Tool Terms of Service | Ultimate Freelancers" />
        <meta property="og:description" content="Terms of Service for Ultimate Freelancers. Free to use with your own API key. No account required." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://ultimatefreelancers.com/terms" />
        <meta name="robots" content="noindex, follow" />
        <script type="application/ld+json">{JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebPage",
          "@id": "https://ultimatefreelancers.com/terms#webpage",
          "url": "https://ultimatefreelancers.com/terms",
          "name": "Free AI Tool Terms of Service | Ultimate Freelancers",
          "description": "Terms of Service for Ultimate Freelancers. Free to use with your own API key. No account, no signup required. Read our full usage and data handling terms.",
          "publisher": { "@id": "https://ultimatefreelancers.com/#organization" },
          "isPartOf": { "@type": "WebSite", "url": "https://ultimatefreelancers.com" },
          "author": { "@type": "Person", "name": "Muhammad Younus", "@id": "https://ultimatefreelancers.com/about#person" }
        })}</script>
      </Helmet>
      <main className="min-h-screen bg-background">
        <div className="container mx-auto px-4 py-16 max-w-3xl">

          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

          <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-lg">
              <strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Ultimate Freelancers ("the Service"), you agree to be bound by these 
                Terms of Service. If you do not agree to these terms, please do not use our Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. Description of Service</h2>
              <p>
                Ultimate Freelancers is an AI-powered platform that helps freelancers create personalized 
                proposals for job postings. The Service analyzes job descriptions and generates tailored 
                proposal content based on your professional profile.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. User Accounts</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You must provide accurate and complete information when creating an account.</li>
                <li>You are responsible for maintaining the security of your account credentials.</li>
                <li>You must notify us immediately of any unauthorized access to your account.</li>
                <li>You must be at least 18 years old to use this Service.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use the Service for any illegal or unauthorized purpose.</li>
                <li>Submit false, misleading, or fraudulent content.</li>
                <li>Attempt to interfere with or disrupt the Service.</li>
                <li>Scrape, copy, or redistribute content without permission.</li>
                <li>Use automated systems to access the Service without authorization.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. Intellectual Property</h2>
              <p>
                The proposals and content generated by our AI are provided for your personal and 
                professional use. You retain ownership of the content you create using our Service. 
                The Ultimate Freelancers platform, including its design, features, and technology, 
                remains our intellectual property.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. AI-Generated Content Disclaimer</h2>
              <p>
                Our AI generates proposals based on the information you provide. While we strive for 
                accuracy and quality, you are responsible for reviewing and editing all generated content 
                before submission. We do not guarantee specific outcomes or results from using our Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Limitation of Liability</h2>
              <p>
                Ultimate Freelancers is provided "as is" without warranties of any kind. We are not 
                liable for any indirect, incidental, or consequential damages arising from your use 
                of the Service, including but not limited to lost profits, job opportunities, or 
                business relationships.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">8. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account at any time for violations 
                of these Terms. You may also delete your account at any time through your account settings.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">9. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. We will notify you of significant changes 
                by email or through the Service. Continued use after changes constitutes acceptance of 
                the new Terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">10. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us at{" "}
                <a href="mailto:support@ultimatefreelancers.com" className="text-primary hover:underline">
                  support@ultimatefreelancers.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <LandingFooter />
    </>
  );
};

export default Terms;
